ARCED_SLIDE_BAR_SELECTOR = ".handleBar-vT4I5"
ARCED_SLIDE_PUZZLE_IMAGE_SELECTOR = "#slider > img"
ARCED_SLIDE_PIECE_CONTAINER_SELECTOR = "#img-button"
ARCED_SLIDE_PIECE_IMAGE_SELECTOR = "#img-button > img"
ARCED_SLIDE_BUTTON_SELECTOR = "#slide-button"

ARCED_SLIDE_SELECTORS = ["#img-button"]
PUZZLE_SELECTORS: list[str] = []
CAPTCHA_WRAPPERS = ["#verification"]


