ARCED_SLIDE_PUZZLE_IMAGE_SELECTOR = "#slider > img"
ARCED_SLIDE_PIECE_CONTAINER_SELECTOR = "#img-button"
ARCED_SLIDE_PIECE_IMAGE_SELECTOR = "#img-button > img"
ARCED_SLIDE_BUTTON_SELECTOR = "#slide-button"
ARCED_SLIDE_UNIQUE_IDENTIFIERS = [".handleBar-vT4I5", ".vT4I57cQ", "div[style=\"width: 414px;\"] #slider", "div[style=\"width: 410px;\"] #slider"]

PUZZLE_BUTTON_SELECTOR = "#slide-button"
PUZZLE_PUZZLE_IMAGE_SELECTOR = "#slider > img"
PUZZLE_PIECE_IMAGE_SELECTOR = "#img-button > img"
PUZZLE_UNIQUE_IDENTIFIERS = ["#Slider"]

SEMANTIC_SHAPES_IFRAME = ".iframe-3eaNR"
SEMANTIC_SHAPES_CHALLENGE_ROOT_ELE = "#Picture"
SEMANTIC_SHAPES_CHALLENGE_TEXT = ".picture-text-2Alt0"
SEMANTIC_SHAPES_IMAGE = "#captchaImg"
SEMANTIC_SHAPES_REFRESH_BUTTON = ".refresh-27d6x"
SEMANTIC_SHAPES_UNIQUE_IDENTIFIERS = [SEMANTIC_SHAPES_IFRAME]

CAPTCHA_PRESENCE_INDICATORS = ["#slide-button", "#Slider", "#slider", SEMANTIC_SHAPES_IFRAME]
